#!/bin/sh
# Gradle wrapper generated by Codex
APP_NAME="NetScan"
APP_BASE_NAME=$(basename "$0")
REPO_ROOT=$(cd "$(dirname "$0")" && pwd)

# Determine Gradle version from properties
GRADLE_VERSION=$(grep "distributionUrl" "$REPO_ROOT/gradle/wrapper/gradle-wrapper.properties" | sed 's/.*gradle-\([0-9.]*\)-.*/\1/')
if [ -z "$GRADLE_VERSION" ]; then
    GRADLE_VERSION="8.5"
fi

GRADLE_HOME="$HOME/.gradle/wrapper/dists/gradle-$GRADLE_VERSION-all"

# Check if gradle is already extracted
GRADLE_BIN=$(find "$GRADLE_HOME" -name "bin/gradle" -type f 2>/dev/null | head -1)
if [ -z "$GRADLE_BIN" ]; then
    # Try system gradle
    GRADLE_BIN=$(which gradle 2>/dev/null)
fi

if [ -n "$GRADLE_BIN" ]; then
    exec "$GRADLE_BIN" "$@"
else
    echo "Gradle not found. Please install Gradle $GRADLE_VERSION or run the GitHub Actions workflow."
    echo "Download from: https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
    exit 1
fi
